### ISSUE TITLE
Insert new FW 682 BMS parameters

### ISSUE THREAD

**Issue by Jusufs** [OpenStuder/openstuder-gateway#9]
On newest firmware, they are some additional parameters:
6075  SOC level for end of charge
6078  Charge current limit ratio
6076  Allow user to define the maximum discharge current of the battery
6077  Maximum discharge current defined by user
6072  Solar Inverter connected on AC-Out
6073  Delta from user frequency to start derating of solar inverter
6074  Delta from user frequency to reach 100% derating of solar inverter
Please insert these in new version.
Thanks.
Jozef

**Comment by Jusufs** [comment]
Replace section BMS parameters,, sorting according modbus apendix 1.6.32 from 19.05.2022
openstuder-gateway/src/drivers/deviceaccess/xcom485i/xcom485ibatterymanager.cpp

* New BMS parameters 6075, 6076, 6077,6078, 6072, 6073, 6074
from line 119
`				// Parameters.
				{140, 6070, SIPropertyType::Float, SIAccessLevel::Expert, SIPropertyFlag::Readable | SIPropertyFlag::Writeable, "SOC level under which battery discharge is stopped", "%"},
                {124, 6062, SIPropertyType::Float, SIAccessLevel::Expert, SIPropertyFlag::Readable | SIPropertyFlag::Writeable, "SOC level for backup", "%"},
                {126, 6063, SIPropertyType::Float, SIAccessLevel::Expert, SIPropertyFlag::Readable | SIPropertyFlag::Writeable, "SOC level for grid feeding", "%"},
                {150, 6075, SIPropertyType::Float, SIAccessLevel::Expert, SIPropertyFlag::Readable | SIPropertyFlag::Writeable, "SOC level for end of charge", "%"},
                {142, 6071, SIPropertyType::Bool, SIAccessLevel::Expert, SIPropertyFlag::Readable | SIPropertyFlag::Writeable, "Use battery priority as energy source when SOC >= SOC for backup (not recommended in parallel)", ""},
                {156, 6078, SIPropertyType::Float, SIAccessLevel::Expert, SIPropertyFlag::Readable | SIPropertyFlag::Writeable, "Charge current limit ratio", "%"},
                {136, 6068, SIPropertyType::Bool, SIAccessLevel::Expert, SIPropertyFlag::Readable | SIPropertyFlag::Writeable, "Allow user to define the maximum charge current of the battery", ""},
                {138, 6069, SIPropertyType::Float, SIAccessLevel::Expert, SIPropertyFlag::Readable | SIPropertyFlag::Writeable, "Allow user to define the maximum discharge current of the battery", ""},
                {152, 6076, SIPropertyType::Bool, SIAccessLevel::Expert, SIPropertyFlag::Readable | SIPropertyFlag::Writeable, "Allow user to define the maximum discharge current of the battery", ""},
                {154, 6077, SIPropertyType::Float, SIAccessLevel::Expert, SIPropertyFlag::Readable | SIPropertyFlag::Writeable, "Maximum discharge current defined by user", "A"},
                {134, 6066, SIPropertyType::Float, SIAccessLevel::Expert,SIPropertyFlag::Readable | SIPropertyFlag::Writeable, "Manufacturer SOC for 100% displayed", "%" },
                {132, 6067, SIPropertyType::Float, SIAccessLevel::Expert,SIPropertyFlag::Readable | SIPropertyFlag::Writeable, "Manufacturer SOC for 0% displayed", "%" },
                {128, 6064, SIPropertyType::Bool, SIAccessLevel::Expert, SIPropertyFlag::Readable | SIPropertyFlag::Writeable, "Use battery current limits instead of recommended values", ""}
                {144, 6072, SIPropertyType::Bool, SIAccessLevel::Expert, SIPropertyFlag::Readable | SIPropertyFlag::Writeable, "Solar Inverter connected on AC-Out", ""},
                {146, 6073, SIPropertyType::Float, SIAccessLevel::Expert, SIPropertyFlag::Readable | SIPropertyFlag::Writeable, "Delta from user frequency to start derating of solar inverter", "Hz"},
                {148, 6074, SIPropertyType::Float, SIAccessLevel::Expert, SIPropertyFlag::Readable | SIPropertyFlag::Writeable, "Delta from user frequency to reach 100% derating of solar inverter", "Hz"}`

**Comment by cm0x4D** [comment]
Implemented in 00d5b3e7d42fa4ca645146825cdd0c9912d6205b, will be in next release.

**Comment by Jusufs** [comment]
Thanks for work
